; Listing generated by Microsoft (R) Optimizing Compiler Version 19.25.28614.0 

	TITLE	C:\고급C\a.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
; File C:\고급C\a.c
_TEXT	SEGMENT
_result$ = -4						; size = 4
_main	PROC

; 4    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 5    : 	int result = SQR(2);

	mov	DWORD PTR _result$[ebp], 4

; 6    : 	return 0;

	xor	eax, eax

; 7    : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
